version: '3'

services: 
  web:
    build: .
    command: python ./todo/manage.py runserver 127.0.0.1:8000
    volumes: 
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres